# Generated by Django 4.0.2 on 2022-02-13 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidnamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], default=('MR', 'Mr.'), max_length=3)),
                ('FirstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('Surname', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=100, verbose_name='Company Name')),
                ('Address', models.CharField(max_length=100)),
                ('Telephone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('BiddingSettings', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default=('HIGH', 'HIGH'), max_length=100, verbose_name='Bidding Settings')),
                ('GoogleID', models.CharField(max_length=100, verbose_name='Google Ads Account ID')),
            ],
        ),
    ]
