# Generated by Django 4.0.2 on 2022-02-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidnamicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidnamic',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
